---

- name: Install wrk for benchmarking
  apt: name=wrk state=present
  become: yes

- name: Add stack repo keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: '{{ stack_repo_key }}'
  become: yes

- name: Add stack deb repo
  apt_repository: repo="deb {{ stack_repo_url }} stable main"
  become: yes

- name: Install stack
  apt: name=stack state=present
  become: yes
  register: stack_install

- name: Check out quorum-tools
  git: repo=ssh://git@github.com/noirqs/quorum-tools.git
       dest='{{ home_dir }}/quorum-tools'
  register: checkout

- name: Setup stack project
  shell: stack setup
  args:
    chdir: '{{ demo_dir }}'
  when: stack_install.changed

- name: Build orchestration code
  shell: stack build
  args:
    chdir: '{{ demo_dir }}'
  when: checkout.changed
