---

- hosts: all
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: which python2 || (sudo apt-get update && sudo apt-get -y install python-simplejson)
      changed_when: False
  roles:
    - { role: common,       tags: ['common'] }
    - { role: node,         tags: ['node'] }
    - { role: orchestrator, tags: ['orch'] }
